server:
  port: 8099
logging:
  config: classpath:logback-boot.xml
spring:
  messages:
    basename: i18n/messages,i18n/common
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000

