server:
  port: 8099
logging:
  config: classpath:logback-boot.xml
spring:
  messages:
    basename: i18n/messages,i18n/common
  thymeleaf:
    prefix: classpath:/templates
    mode: HTML5
    cache: false
    encoding: UTF-8
